### ISSUE TITLE
텐서플로우 이미지(kernel-python-tensorflow:1.8-py36)에 문제가 있어요  

### ISSUE THREAD

**Issue by jams777** [lablup/backend.ai-kernels#85]
우선 해당 이미지를 가져왔습니다.
docker pull lablup/kernel-python-tensorflow:1.8-py36

그리고 test.py 파일을 만들어서 실행했어요
내용은 
```python
import tensorflow as tf
print(tf.__version__)
print('hello')
```
실행은 아래처럼 했어요. 그랬더니 에러가 납니다.
```
$> backend.ai run --rm --exec 'python test.py' python-tensorflow:1.8-py36 test.py
✔ Session ae7f5614dc340f84aca9037d242910d2 is ready.
Uploading files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 63.0/63.0 [00:00<00:00, 543bytes/s, file=test.py]
✔ Uploading done.
python-kernel: skipping build phase due to missing "setup.py" file
✔ Build finished. (exit code = 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by achimnol** [comment]
재현 확인했습니다. TensorFlow wheel 빌드용 common 이미지와 runtime용 이미지의 glibc 호환 이슈로 보입니다.

**Comment by achimnol** [comment]
`lablup/kernel-python-tensorflow:1.7-py36` 커널로는 잘 됩니다.
일단 테스트해보시려면 그 이미지를 받아서 사용하시면 되겠습니다.

**Comment by hephaex** [comment]
2f18275
